{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "petclinic.serviceAccountName" . }}
  namespace: {{ .Values.Namespace }}
  labels:
{{ include "petclinic.labels" . | indent 4 }}
{{- end -}}
